package aqueduct

// These types were generated by jsongen and then tweaked

// Frontend
type Frontend struct {
	Backend   string        `json:"backend"`
	Bind      string        `json:"bind"`
	Id        string        `json:"id,omitempty"`
	Keepalive string        `json:"keepalive,omitempty"`
	Key       string        `json:"key,omitempty"`
	Mode      string        `json:"mode"`
	Natives   []interface{} `json:"natives,omitempty"`
	Rules     []Rule        `json:"rules,omitempty"`
	Type      string        `json:"_type,omitempty"`
}

// A Routing Rule
type Rule struct {
	Backend   string `json:"backend"`
	Header    string `json:"header"`
	Operation string `json:"operation"`
	Type      string `json:"type"`
	Value     string `json:"value"`
}

type Member struct {
	Host      string `json:"host"`
	Id        string `json:"id"`
	LastKnown int64  `json:"lastKnown"`
	Meta      Meta   `json:"meta"`
	Name      string `json:"name"`
	Port      int64  `json:"port"`
	Version   string `json:"version"`
}

type Meta struct {
	Hostname   string `json:"hostname"`
	Pid        int64  `json:"pid"`
	Registered int64  `json:"registered"`
}

// Backend
type Backend struct {
	Balance string        `json:"balance,omitempty"`
	Host    interface{}   `json:"host,omitempty"`
	Id      string        `json:"id,omitempty"`
	Key     string        `json:"key,omitempty"`
	Members []Member      `json:"members"`
	Mode    string        `json:"mode"`
	Name    string        `json:"name,omitempty"`
	Natives []interface{} `json:"natives,omitempty"`
	Type    string        `json:"type,omitempty"`
	Version string        `json:"version,omitempty"`
}
